services:
  app:
    build:
      context: .
      dockerfile: ./.config/docker/node/Dockerfile.local
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=local
